### ISSUE TITLE
Unable to replicate DeepLog 

### ISSUE THREAD

**Issue by alishan2040** [Wapiti08/LogAnalyzer#14]
Hi @Wapiti08, thanks for providing this implementation with the support for parameter value anomaly detection.

I started following the instructions provided in the readme. 
Step 1: Log parsing: It worked perfect on Clear logs while faced some errors on Malicious. Was it normal? Please check the screenshot below
![image](https://user-images.githubusercontent.com/30209002/189493346-88fe6280-4a74-4a46-9997-0722c9ffbff8.png)
After this step, entries in generated `Integrated_structured_log.csv` (2606 entries) were not matching with existing Integrated_structured_log.csv (1131 entries) from `Deeplog_demo/Dataset/Linux/Malicious`. Although I ran the code on the same dataset with same settings.

Step 2: Generate log value vector: Moving onto the next step, provided the same structured.csv.

![image](https://user-images.githubusercontent.com/30209002/189493792-5f0a24d3-5771-47f6-9281-7e2221ab1c0b.png)
No Error at this stage but entries didn't match between new and existing log_value_vector.csv. Also the data format and values were different.
Few lines from newly generated `log_value_vector.csv`:
![image](https://user-images.githubusercontent.com/30209002/189493995-f39f7ef3-bd35-4a88-9238-5477f797c604.png)

Few lines from existing `log_value_vector.csv` [:](https://github.com/Wapiti08/DeepLog/blob/master/Deeplog_demo/Dataset/Linux/Malicious_Separate_Structured_Logs/log_value_vector.csv)
![image](https://user-images.githubusercontent.com/30209002/189494024-c397c26b-6ed5-4b07-ba4f-e696c358ffe2.png)

Step 3:  Generate Log key Matrix: (need to test parameter value anomaly detection)

![image](https://user-images.githubusercontent.com/30209002/189494454-9e7ac60c-938d-4591-9f03-b23554b1e27d.png)
![image](https://user-images.githubusercontent.com/30209002/189494482-d56d9d98-0200-4411-b487-9980eb3f0f5d.png)

Error here:
![image](https://user-images.githubusercontent.com/30209002/189494497-85798da8-f7a0-4f47-ba79-8dee33c9d4c1.png)

It was quite surprising for me to see different outputs by running the same code on the same dataset. Am I missing something? Please guide on the exact flow for running this code. 
Thanks,

**Comment by Wapiti08** [comment]
Hi,

Thanks for the trying this resp. Please use Drain module instead of LenMa. Apart from that, I did not check code in demo, it was quite old work. Please follow instructions on separate module folders. 

Apart from that, it is normal to meet some errors during the parsing.

**Comment by alishan2040** [comment]
@Wapiti08 
How these constants (false positives, true positives) were defined or calculated and turned into probabilities before being used in anomaly_match in Parameter_Value_Vector.py?
`fp_int = 0.97`
`tp_int = 0.999`
`attempts = 10`
`threshold1, threshold3, seq_pre_dict = anomaly_match(mse_error, fp_int, tp_int, eventId)`

I'm referring to this file: https://github.com/Wapiti08/DeepLog/blob/master/Parameter_Value_Vector/Parameter_Value_Vector.py

Thanks,

**Comment by Wapiti08** [comment]
You can check my reference (Deeplog) where the ideas came from. The threshold is given from that paper. The attempts are what I defined to retrain the new patterns/data (as part of online learning.) But I recommend you to apply Elastic Weight Consolidation to avoid catastrophic forgetting problem. I am generating a paper now. Maybe I will attach published version after months.

**Comment by Wapiti08** [comment]
> @Wapiti08 How these constants (false positives, true positives) were defined or calculated and turned into probabilities before being used in anomaly_match in Parameter_Value_Vector.py? `fp_int = 0.97` `tp_int = 0.999` `attempts = 10` `threshold1, threshold3, seq_pre_dict = anomaly_match(mse_error, fp_int, tp_int, eventId)`
> 
> I'm referring to this file: https://github.com/Wapiti08/DeepLog/blob/master/Parameter_Value_Vector/Parameter_Value_Vector.py
> 
> Thanks,

You can check my reference (Deeplog) where the ideas came from. The threshold is given from that paper. The attempts are what I defined to retrain the new patterns/data (as part of online learning.) But I recommend you to apply Elastic Weight Consolidation to avoid catastrophic forgetting problem. I am generating a paper now. Maybe I will attach published version after months.
