### ISSUE TITLE
Path Sequence?

### ISSUE THREAD

**Issue by utkarshgupta2504** [Wapiti08/LogAnalyzer#15]
Hey, thank you for the wonderful work!

I had a doubt, I was trying to run the code, successfully generated the integrated structured logs

But when I try to run the Execution Path Anomaly, I am stuck, where the program cannot find the files ".../Path_sequence.csv"

I tried searching the project where it will be generated, but could not find it anywhere, can you help me understand the role of the file? And how can I generate it?

**Comment by Wapiti08** [comment]
You have to use module inside Logparse to parse your logs first. It will generate corresponding files. Then it is the anomaly detection part

**Comment by utkarshgupta2504** [comment]
Yup, thank you I got it, I did not observe a numpy error and that was the cause of the complete error
